//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoveCal.Resourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LoveMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoveMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoveCal.Resourses.LoveMessage", typeof(LoveMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A combination of number 1 with number 1 is very beneficial for business but it is often not as good for personal relationships..
        /// </summary>
        public static string LoveMessage_1_1 {
            get {
                return ResourceManager.GetString("LoveMessage_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A relationship with a combination of these numbers is always preferable and good..
        /// </summary>
        public static string LoveMessage_1_2 {
            get {
                return ResourceManager.GetString("LoveMessage_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The problems that arise with a combination of number 1 and number 3 are that people can be egoistic and self-centered..
        /// </summary>
        public static string LoveMessage_1_3 {
            get {
                return ResourceManager.GetString("LoveMessage_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A relationship based on the combination of these two numbers has opposing but complementary qualities..
        /// </summary>
        public static string LoveMessage_1_4 {
            get {
                return ResourceManager.GetString("LoveMessage_1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A relationship based on the combination of these two numbers has opposing but complementary qualities..
        /// </summary>
        public static string LoveMessage_1_5 {
            get {
                return ResourceManager.GetString("LoveMessage_1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These two people are capable of great prosperity as long as they are together..
        /// </summary>
        public static string LoveMessage_1_6 {
            get {
                return ResourceManager.GetString("LoveMessage_1_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This match may also result in a life-long friendship..
        /// </summary>
        public static string LoveMessage_1_7 {
            get {
                return ResourceManager.GetString("LoveMessage_1_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This combination is actually a perfect mix of love and hate..
        /// </summary>
        public static string LoveMessage_1_8 {
            get {
                return ResourceManager.GetString("LoveMessage_1_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This association makes a great relationship..
        /// </summary>
        public static string LoveMessage_1_9 {
            get {
                return ResourceManager.GetString("LoveMessage_1_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A relationship with a combination of these numbers is always preferable and good..
        /// </summary>
        public static string LoveMessage_2_1 {
            get {
                return ResourceManager.GetString("LoveMessage_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both partners are the same in this combination..
        /// </summary>
        public static string LoveMessage_2_2 {
            get {
                return ResourceManager.GetString("LoveMessage_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usually have a good humor and chemistry in the relationship..
        /// </summary>
        public static string LoveMessage_2_3 {
            get {
                return ResourceManager.GetString("LoveMessage_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This association is good for a relationship and it helps people to live their live peacefully..
        /// </summary>
        public static string LoveMessage_2_4 {
            get {
                return ResourceManager.GetString("LoveMessage_2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chemistry in this relationship has to be very strong so that the opposing natures do not collide with each other..
        /// </summary>
        public static string LoveMessage_2_5 {
            get {
                return ResourceManager.GetString("LoveMessage_2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both these people should be understanding and should watch their decisions and behaviour..
        /// </summary>
        public static string LoveMessage_2_6 {
            get {
                return ResourceManager.GetString("LoveMessage_2_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This association is believed to be very fruitful..
        /// </summary>
        public static string LoveMessage_2_7 {
            get {
                return ResourceManager.GetString("LoveMessage_2_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is believed that this is one of the most compatible love relationships according to numerology..
        /// </summary>
        public static string LoveMessage_2_8 {
            get {
                return ResourceManager.GetString("LoveMessage_2_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These two numbers act as two bodies with one soul when in a relationship..
        /// </summary>
        public static string LoveMessage_2_9 {
            get {
                return ResourceManager.GetString("LoveMessage_2_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The problems that arise with a combination of number 1 and number 3 are that people can be egoistic and self-centered..
        /// </summary>
        public static string LoveMessage_3_1 {
            get {
                return ResourceManager.GetString("LoveMessage_3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usually have a good humor and chemistry in the relationship..
        /// </summary>
        public static string LoveMessage_3_2 {
            get {
                return ResourceManager.GetString("LoveMessage_3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These numbers should be understanding and should give freedom to one another..
        /// </summary>
        public static string LoveMessage_3_3 {
            get {
                return ResourceManager.GetString("LoveMessage_3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without proper understanding, this relationship will also face problems like any other..
        /// </summary>
        public static string LoveMessage_3_4 {
            get {
                return ResourceManager.GetString("LoveMessage_3_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The two people will find each other very interesting and will be able to entertain each other forever..
        /// </summary>
        public static string LoveMessage_3_5 {
            get {
                return ResourceManager.GetString("LoveMessage_3_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chemistry is usually very strong and durable..
        /// </summary>
        public static string LoveMessage_3_6 {
            get {
                return ResourceManager.GetString("LoveMessage_3_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The two numbers are exactly opposite and some believe that they are incompatible..
        /// </summary>
        public static string LoveMessage_3_7 {
            get {
                return ResourceManager.GetString("LoveMessage_3_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This association usually requires an extra effort from both sides in order to live in harmony..
        /// </summary>
        public static string LoveMessage_3_8 {
            get {
                return ResourceManager.GetString("LoveMessage_3_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Their emotions and passions are well-matched with each other..
        /// </summary>
        public static string LoveMessage_3_9 {
            get {
                return ResourceManager.GetString("LoveMessage_3_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In a relationship like this differences may arise due to the different personalities..
        /// </summary>
        public static string LoveMessage_4_1 {
            get {
                return ResourceManager.GetString("LoveMessage_4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an excellent combination..
        /// </summary>
        public static string LoveMessage_4_2 {
            get {
                return ResourceManager.GetString("LoveMessage_4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is because most of the characteristics will be opposite and dissimilar..
        /// </summary>
        public static string LoveMessage_4_3 {
            get {
                return ResourceManager.GetString("LoveMessage_4_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both of these people share the same values and goals in life..
        /// </summary>
        public static string LoveMessage_4_4 {
            get {
                return ResourceManager.GetString("LoveMessage_4_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The characteristics of both people will be very different..
        /// </summary>
        public static string LoveMessage_4_5 {
            get {
                return ResourceManager.GetString("LoveMessage_4_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This relationship is built on mutual trust and values. It is a solid relationship..
        /// </summary>
        public static string LoveMessage_4_6 {
            get {
                return ResourceManager.GetString("LoveMessage_4_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both these people are also very well-coordinated..
        /// </summary>
        public static string LoveMessage_4_7 {
            get {
                return ResourceManager.GetString("LoveMessage_4_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both of these have absolutely the same nature..
        /// </summary>
        public static string LoveMessage_4_8 {
            get {
                return ResourceManager.GetString("LoveMessage_4_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both the numbers are good in their own ways..
        /// </summary>
        public static string LoveMessage_4_9 {
            get {
                return ResourceManager.GetString("LoveMessage_4_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This relationship can be vibrant and lively sometimes..
        /// </summary>
        public static string LoveMessage_5_1 {
            get {
                return ResourceManager.GetString("LoveMessage_5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This can be a great relationship with proper understanding..
        /// </summary>
        public static string LoveMessage_5_2 {
            get {
                return ResourceManager.GetString("LoveMessage_5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This association is considered to be one of the best combinations which never faces a boring time in life..
        /// </summary>
        public static string LoveMessage_5_3 {
            get {
                return ResourceManager.GetString("LoveMessage_5_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The characteristics of both people will be very different..
        /// </summary>
        public static string LoveMessage_5_4 {
            get {
                return ResourceManager.GetString("LoveMessage_5_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both these people should understand each other and try to maintain some distance in order to have a happy married life..
        /// </summary>
        public static string LoveMessage_5_5 {
            get {
                return ResourceManager.GetString("LoveMessage_5_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both the people in this association need to make compromises for success in this relationship..
        /// </summary>
        public static string LoveMessage_5_6 {
            get {
                return ResourceManager.GetString("LoveMessage_5_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The best possible relationship will be as friends..
        /// </summary>
        public static string LoveMessage_5_7 {
            get {
                return ResourceManager.GetString("LoveMessage_5_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This combination brings out the best in each other..
        /// </summary>
        public static string LoveMessage_5_8 {
            get {
                return ResourceManager.GetString("LoveMessage_5_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a relationship between two who may find it hard to work the relationship into their busy schedules..
        /// </summary>
        public static string LoveMessage_5_9 {
            get {
                return ResourceManager.GetString("LoveMessage_5_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These two people are capable of great prosperity as long as they are together..
        /// </summary>
        public static string LoveMessage_6_1 {
            get {
                return ResourceManager.GetString("LoveMessage_6_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both these people should be understanding and should watch their decisions and behaviour..
        /// </summary>
        public static string LoveMessage_6_2 {
            get {
                return ResourceManager.GetString("LoveMessage_6_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chemistry is usually very strong and durable..
        /// </summary>
        public static string LoveMessage_6_3 {
            get {
                return ResourceManager.GetString("LoveMessage_6_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This relationship is built on mutual trust and values..
        /// </summary>
        public static string LoveMessage_6_4 {
            get {
                return ResourceManager.GetString("LoveMessage_6_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both the people in this association need to make compromises for success in this relationship..
        /// </summary>
        public static string LoveMessage_6_5 {
            get {
                return ResourceManager.GetString("LoveMessage_6_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both the people will be completely balanced..
        /// </summary>
        public static string LoveMessage_6_6 {
            get {
                return ResourceManager.GetString("LoveMessage_6_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some believe that this relationship may require too much compromises on both the parts..
        /// </summary>
        public static string LoveMessage_6_7 {
            get {
                return ResourceManager.GetString("LoveMessage_6_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This combination is usually recommended for marriage and romance..
        /// </summary>
        public static string LoveMessage_6_8 {
            get {
                return ResourceManager.GetString("LoveMessage_6_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People in this association will enjoy a happy and peaceful time together..
        /// </summary>
        public static string LoveMessage_6_9 {
            get {
                return ResourceManager.GetString("LoveMessage_6_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This match may also result in a life-long friendship..
        /// </summary>
        public static string LoveMessage_7_1 {
            get {
                return ResourceManager.GetString("LoveMessage_7_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The characteristics of both these numbers are almost same..
        /// </summary>
        public static string LoveMessage_7_2 {
            get {
                return ResourceManager.GetString("LoveMessage_7_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The two numbers are exactly opposite and some believe that they are incompatible..
        /// </summary>
        public static string LoveMessage_7_3 {
            get {
                return ResourceManager.GetString("LoveMessage_7_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some believe that such an association may not be successful due to the lack of energy..
        /// </summary>
        public static string LoveMessage_7_4 {
            get {
                return ResourceManager.GetString("LoveMessage_7_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The best possible relationship will be as friends..
        /// </summary>
        public static string LoveMessage_7_5 {
            get {
                return ResourceManager.GetString("LoveMessage_7_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some believe that this relationship may require too much compromises on both the parts..
        /// </summary>
        public static string LoveMessage_7_6 {
            get {
                return ResourceManager.GetString("LoveMessage_7_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Therefore, this is a very compatible pairing..
        /// </summary>
        public static string LoveMessage_7_7 {
            get {
                return ResourceManager.GetString("LoveMessage_7_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This relationship often lacks emotion..
        /// </summary>
        public static string LoveMessage_7_8 {
            get {
                return ResourceManager.GetString("LoveMessage_7_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This relationship is considered to be very successful..
        /// </summary>
        public static string LoveMessage_7_9 {
            get {
                return ResourceManager.GetString("LoveMessage_7_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both these numbers are materialistic numbers who look forward to acquiring wealth..
        /// </summary>
        public static string LoveMessage_8_1 {
            get {
                return ResourceManager.GetString("LoveMessage_8_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is believed that this is one of the most compatible love relationships according to numerology..
        /// </summary>
        public static string LoveMessage_8_2 {
            get {
                return ResourceManager.GetString("LoveMessage_8_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This association usually requires an extra effort from both sides in order to live in harmony..
        /// </summary>
        public static string LoveMessage_8_3 {
            get {
                return ResourceManager.GetString("LoveMessage_8_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both of these have absolutely the same nature..
        /// </summary>
        public static string LoveMessage_8_4 {
            get {
                return ResourceManager.GetString("LoveMessage_8_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This combination brings out the best in each other..
        /// </summary>
        public static string LoveMessage_8_5 {
            get {
                return ResourceManager.GetString("LoveMessage_8_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This combination is usually recommended for marriage and romance..
        /// </summary>
        public static string LoveMessage_8_6 {
            get {
                return ResourceManager.GetString("LoveMessage_8_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This association can turn into a very successful..
        /// </summary>
        public static string LoveMessage_8_7 {
            get {
                return ResourceManager.GetString("LoveMessage_8_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Therefore, both these people will have a drive to be very successful..
        /// </summary>
        public static string LoveMessage_8_8 {
            get {
                return ResourceManager.GetString("LoveMessage_8_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This association is considered to be very good for romance..
        /// </summary>
        public static string LoveMessage_8_9 {
            get {
                return ResourceManager.GetString("LoveMessage_8_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a great understanding between the people ..
        /// </summary>
        public static string LoveMessage_9_1 {
            get {
                return ResourceManager.GetString("LoveMessage_9_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These two numbers act as two bodies with one soul when in a relationship..
        /// </summary>
        public static string LoveMessage_9_2 {
            get {
                return ResourceManager.GetString("LoveMessage_9_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Their emotions and passions are well-matched with each other..
        /// </summary>
        public static string LoveMessage_9_3 {
            get {
                return ResourceManager.GetString("LoveMessage_9_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These people are focused on the basics of building a secure and solid immediate world..
        /// </summary>
        public static string LoveMessage_9_4 {
            get {
                return ResourceManager.GetString("LoveMessage_9_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These two numbers can make good business partners as well as friends..
        /// </summary>
        public static string LoveMessage_9_5 {
            get {
                return ResourceManager.GetString("LoveMessage_9_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These two people forge some form of a relationship that goes on for a lifetime..
        /// </summary>
        public static string LoveMessage_9_6 {
            get {
                return ResourceManager.GetString("LoveMessage_9_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They are listed neutral because the relationship can go either way depending largely on spiritual beliefs..
        /// </summary>
        public static string LoveMessage_9_7 {
            get {
                return ResourceManager.GetString("LoveMessage_9_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This association is considered to be very good for romance..
        /// </summary>
        public static string LoveMessage_9_8 {
            get {
                return ResourceManager.GetString("LoveMessage_9_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These two become passionate lovers or very good friends with each other..
        /// </summary>
        public static string LoveMessage_9_9 {
            get {
                return ResourceManager.GetString("LoveMessage_9_9", resourceCulture);
            }
        }
    }
}
