//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoveCal.Resourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoveCal.Resourses.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Your Love percentage .
        /// </summary>
        public static string button1_Message {
            get {
                return ResourceManager.GetString("button1_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display the Love Message .
        /// </summary>
        public static string button2_Message {
            get {
                return ResourceManager.GetString("button2_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Your Romantic Location.
        /// </summary>
        public static string button3_Message {
            get {
                return ResourceManager.GetString("button3_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Percentage.
        /// </summary>
        public static string button4_Message {
            get {
                return ResourceManager.GetString("button4_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male Selected.
        /// </summary>
        public static string Gender_Boys_message {
            get {
                return ResourceManager.GetString("Gender_Boys_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female Selected .
        /// </summary>
        public static string Gender_Girl_message {
            get {
                return ResourceManager.GetString("Gender_Girl_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names should not be Empty.
        /// </summary>
        public static string InputEmpty_Message {
            get {
                return ResourceManager.GetString("InputEmpty_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names can not be Numeric Value.
        /// </summary>
        public static string InputNumeric_Message {
            get {
                return ResourceManager.GetString("InputNumeric_Message", resourceCulture);
            }
        }
    }
}
