//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoveCal.Resourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlacesMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlacesMsg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoveCal.Resourses.PlacesMsg", typeof(PlacesMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city is nestled in the lush greenery where landscape is surrounded by mountains offering a majestic vie during sunrise..
        /// </summary>
        public static string PlaceMsg_1_1 {
            get {
                return ResourceManager.GetString("PlaceMsg_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is the commercial capital of the country..
        /// </summary>
        public static string PlaceMsg_1_2 {
            get {
                return ResourceManager.GetString("PlaceMsg_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name Samanala Kanda mean Butterfly Mountain..
        /// </summary>
        public static string PlaceMsg_1_3 {
            get {
                return ResourceManager.GetString("PlaceMsg_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city is nestled in the lush greenery where landscape is surrounded by mountains offering a majestic vie during sunrise..
        /// </summary>
        public static string PlaceMsg_1_4 {
            get {
                return ResourceManager.GetString("PlaceMsg_1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The climate of this place is moderate and can be visited at any time of the year..
        /// </summary>
        public static string PlaceMsg_1_5 {
            get {
                return ResourceManager.GetString("PlaceMsg_1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bentota is a coastal city located in the Southern Province..
        /// </summary>
        public static string PlaceMsg_1_6 {
            get {
                return ResourceManager.GetString("PlaceMsg_1_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is a mountain station at 1,868 m (6,128 ft) of altitude, in a splendid landscape..
        /// </summary>
        public static string PlaceMsg_1_7 {
            get {
                return ResourceManager.GetString("PlaceMsg_1_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city is nestled in the lush greenery where landscape is surrounded by mountains offering a majestic vie during sunrise..
        /// </summary>
        public static string PlaceMsg_1_8 {
            get {
                return ResourceManager.GetString("PlaceMsg_1_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is the commercial capital of the country..
        /// </summary>
        public static string PlaceMsg_1_9 {
            get {
                return ResourceManager.GetString("PlaceMsg_1_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bentota is a coastal city located in the Southern Province..
        /// </summary>
        public static string PlaceMsg_2_1 {
            get {
                return ResourceManager.GetString("PlaceMsg_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A  surfer town with its sandy beaches, sea-side resorts and discos..
        /// </summary>
        public static string PlaceMsg_2_2 {
            get {
                return ResourceManager.GetString("PlaceMsg_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is a mountain station at 1,868 m (6,128 ft) of altitude, in a splendid landscape..
        /// </summary>
        public static string PlaceMsg_2_3 {
            get {
                return ResourceManager.GetString("PlaceMsg_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is most popular for its golden beach that stretches a mile and some world-class hotels..
        /// </summary>
        public static string PlaceMsg_2_4 {
            get {
                return ResourceManager.GetString("PlaceMsg_2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is a mountain station at 1,868 m (6,128 ft) of altitude, in a splendid landscape..
        /// </summary>
        public static string PlaceMsg_2_5 {
            get {
                return ResourceManager.GetString("PlaceMsg_2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bentota is a coastal city located in the Southern Province..
        /// </summary>
        public static string PlaceMsg_2_6 {
            get {
                return ResourceManager.GetString("PlaceMsg_2_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is the commercial capital of the country..
        /// </summary>
        public static string PlaceMsg_2_7 {
            get {
                return ResourceManager.GetString("PlaceMsg_2_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bentota is a coastal city located in the Southern Province..
        /// </summary>
        public static string PlaceMsg_2_8 {
            get {
                return ResourceManager.GetString("PlaceMsg_2_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is a mountain station at 1,868 m (6,128 ft) of altitude, in a splendid landscape..
        /// </summary>
        public static string PlaceMsg_2_9 {
            get {
                return ResourceManager.GetString("PlaceMsg_2_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thus with a cultural heritage city this city also has some of the significant historical sites that are worth visiting..
        /// </summary>
        public static string PlaceMsg_3_1 {
            get {
                return ResourceManager.GetString("PlaceMsg_3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bentota is a coastal city located in the Southern Province..
        /// </summary>
        public static string PlaceMsg_3_2 {
            get {
                return ResourceManager.GetString("PlaceMsg_3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is the commercial capital of the country..
        /// </summary>
        public static string PlaceMsg_3_3 {
            get {
                return ResourceManager.GetString("PlaceMsg_3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close to this city there are historical sites that are worth watching and reflect the past of this place..
        /// </summary>
        public static string PlaceMsg_3_4 {
            get {
                return ResourceManager.GetString("PlaceMsg_3_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is located in the center of the country amongst the hills of the Kandy Valley..
        /// </summary>
        public static string PlaceMsg_3_5 {
            get {
                return ResourceManager.GetString("PlaceMsg_3_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bentota is a coastal city located in the Southern Province..
        /// </summary>
        public static string PlaceMsg_3_6 {
            get {
                return ResourceManager.GetString("PlaceMsg_3_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close to this city there are historical sites that are worth watching and reflect the past of this place..
        /// </summary>
        public static string PlaceMsg_3_7 {
            get {
                return ResourceManager.GetString("PlaceMsg_3_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city is nestled in the lush greenery where landscape is surrounded by mountains offering a majestic vie during sunrise..
        /// </summary>
        public static string PlaceMsg_3_8 {
            get {
                return ResourceManager.GetString("PlaceMsg_3_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bentota is a coastal city located in the Southern Province..
        /// </summary>
        public static string PlaceMsg_3_9 {
            get {
                return ResourceManager.GetString("PlaceMsg_3_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city is nestled in the lush greenery where landscape is surrounded by mountains offering a majestic vie during sunrise..
        /// </summary>
        public static string PlaceMsg_4_1 {
            get {
                return ResourceManager.GetString("PlaceMsg_4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bentota is a coastal city located in the Southern Province..
        /// </summary>
        public static string PlaceMsg_4_2 {
            get {
                return ResourceManager.GetString("PlaceMsg_4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thus with a cultural heritage city this city also has some of the significant historical sites that are worth visiting..
        /// </summary>
        public static string PlaceMsg_4_3 {
            get {
                return ResourceManager.GetString("PlaceMsg_4_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is the commercial capital of the country..
        /// </summary>
        public static string PlaceMsg_4_4 {
            get {
                return ResourceManager.GetString("PlaceMsg_4_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city is nestled in the lush greenery where landscape is surrounded by mountains offering a majestic vie during sunrise..
        /// </summary>
        public static string PlaceMsg_4_5 {
            get {
                return ResourceManager.GetString("PlaceMsg_4_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A  surfer town with its sandy beaches, sea-side resorts and discos..
        /// </summary>
        public static string PlaceMsg_4_6 {
            get {
                return ResourceManager.GetString("PlaceMsg_4_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is located in the center of the country amongst the hills of the Kandy Valley..
        /// </summary>
        public static string PlaceMsg_4_7 {
            get {
                return ResourceManager.GetString("PlaceMsg_4_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is located in the center of the country amongst the hills of the Kandy Valley..
        /// </summary>
        public static string PlaceMsg_4_8 {
            get {
                return ResourceManager.GetString("PlaceMsg_4_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city is nestled in the lush greenery where landscape is surrounded by mountains offering a majestic vie during sunrise..
        /// </summary>
        public static string PlaceMsg_4_9 {
            get {
                return ResourceManager.GetString("PlaceMsg_4_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A  surfer town with its sandy beaches, sea-side resorts and discos..
        /// </summary>
        public static string PlaceMsg_5_1 {
            get {
                return ResourceManager.GetString("PlaceMsg_5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A  surfer town with its sandy beaches, sea-side resorts and discos..
        /// </summary>
        public static string PlaceMsg_5_2 {
            get {
                return ResourceManager.GetString("PlaceMsg_5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bentota is a coastal city located in the Southern Province..
        /// </summary>
        public static string PlaceMsg_5_3 {
            get {
                return ResourceManager.GetString("PlaceMsg_5_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city is nestled in the lush greenery where landscape is surrounded by mountains offering a majestic vie during sunrise..
        /// </summary>
        public static string PlaceMsg_5_4 {
            get {
                return ResourceManager.GetString("PlaceMsg_5_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city is nestled in the lush greenery where landscape is surrounded by mountains offering a majestic vie during sunrise..
        /// </summary>
        public static string PlaceMsg_5_5 {
            get {
                return ResourceManager.GetString("PlaceMsg_5_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is located in the center of the country amongst the hills of the Kandy Valley..
        /// </summary>
        public static string PlaceMsg_5_6 {
            get {
                return ResourceManager.GetString("PlaceMsg_5_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is located in the center of the country amongst the hills of the Kandy Valley..
        /// </summary>
        public static string PlaceMsg_5_7 {
            get {
                return ResourceManager.GetString("PlaceMsg_5_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bentota is a coastal city located in the Southern Province..
        /// </summary>
        public static string PlaceMsg_5_8 {
            get {
                return ResourceManager.GetString("PlaceMsg_5_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galle is declared as World Heritage City by the UNESCO and is surrounded by beaches..
        /// </summary>
        public static string PlaceMsg_5_9 {
            get {
                return ResourceManager.GetString("PlaceMsg_5_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is the commercial capital of the country..
        /// </summary>
        public static string PlaceMsg_6_1 {
            get {
                return ResourceManager.GetString("PlaceMsg_6_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is located in the center of the country amongst the hills of the Kandy Valley..
        /// </summary>
        public static string PlaceMsg_6_2 {
            get {
                return ResourceManager.GetString("PlaceMsg_6_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is the commercial capital of the country..
        /// </summary>
        public static string PlaceMsg_6_3 {
            get {
                return ResourceManager.GetString("PlaceMsg_6_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is a mountain station at 1,868 m (6,128 ft) of altitude, in a splendid landscape..
        /// </summary>
        public static string PlaceMsg_6_4 {
            get {
                return ResourceManager.GetString("PlaceMsg_6_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galle is declared as World Heritage City by the UNESCO and is surrounded by beaches..
        /// </summary>
        public static string PlaceMsg_6_5 {
            get {
                return ResourceManager.GetString("PlaceMsg_6_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A  surfer town with its sandy beaches, sea-side resorts and discos..
        /// </summary>
        public static string PlaceMsg_6_6 {
            get {
                return ResourceManager.GetString("PlaceMsg_6_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The climate of this place is moderate and can be visited at any time of the year..
        /// </summary>
        public static string PlaceMsg_6_7 {
            get {
                return ResourceManager.GetString("PlaceMsg_6_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is a mountain station at 1,868 m (6,128 ft) of altitude, in a splendid landscape..
        /// </summary>
        public static string PlaceMsg_6_8 {
            get {
                return ResourceManager.GetString("PlaceMsg_6_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A  surfer town with its sandy beaches, sea-side resorts and discos..
        /// </summary>
        public static string PlaceMsg_6_9 {
            get {
                return ResourceManager.GetString("PlaceMsg_6_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is located in the center of the country amongst the hills of the Kandy Valley..
        /// </summary>
        public static string PlaceMsg_7_1 {
            get {
                return ResourceManager.GetString("PlaceMsg_7_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The climate of this place is moderate and can be visited at any time of the year..
        /// </summary>
        public static string PlaceMsg_7_2 {
            get {
                return ResourceManager.GetString("PlaceMsg_7_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city is nestled in the lush greenery where landscape is surrounded by mountains offering a majestic vie during sunrise..
        /// </summary>
        public static string PlaceMsg_7_3 {
            get {
                return ResourceManager.GetString("PlaceMsg_7_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The climate of this place is moderate and can be visited at any time of the year..
        /// </summary>
        public static string PlaceMsg_7_4 {
            get {
                return ResourceManager.GetString("PlaceMsg_7_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is located in the center of the country amongst the hills of the Kandy Valley..
        /// </summary>
        public static string PlaceMsg_7_5 {
            get {
                return ResourceManager.GetString("PlaceMsg_7_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The climate of this place is moderate and can be visited at any time of the year..
        /// </summary>
        public static string PlaceMsg_7_6 {
            get {
                return ResourceManager.GetString("PlaceMsg_7_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is located in the center of the country amongst the hills of the Kandy Valley.
        /// </summary>
        public static string PlaceMsg_7_7 {
            get {
                return ResourceManager.GetString("PlaceMsg_7_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is the commercial capital of the country..
        /// </summary>
        public static string PlaceMsg_7_8 {
            get {
                return ResourceManager.GetString("PlaceMsg_7_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is a mountain station at 1,868 m (6,128 ft) of altitude, in a splendid landscape..
        /// </summary>
        public static string PlaceMsg_7_9 {
            get {
                return ResourceManager.GetString("PlaceMsg_7_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is the commercial capital of the country..
        /// </summary>
        public static string PlaceMsg_8_1 {
            get {
                return ResourceManager.GetString("PlaceMsg_8_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is a mountain station at 1,868 m (6,128 ft) of altitude, in a splendid landscape..
        /// </summary>
        public static string PlaceMsg_8_2 {
            get {
                return ResourceManager.GetString("PlaceMsg_8_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city is nestled in the lush greenery where landscape is surrounded by mountains offering a majestic vie during sunrise..
        /// </summary>
        public static string PlaceMsg_8_3 {
            get {
                return ResourceManager.GetString("PlaceMsg_8_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A  surfer town with its sandy beaches, sea-side resorts and discos..
        /// </summary>
        public static string PlaceMsg_8_4 {
            get {
                return ResourceManager.GetString("PlaceMsg_8_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is a mountain station at 1,868 m (6,128 ft) of altitude, in a splendid landscape..
        /// </summary>
        public static string PlaceMsg_8_5 {
            get {
                return ResourceManager.GetString("PlaceMsg_8_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is most popular for its golden beach that stretches a mile and some world-class hotels..
        /// </summary>
        public static string PlaceMsg_8_6 {
            get {
                return ResourceManager.GetString("PlaceMsg_8_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bentota is a coastal city located in the Southern Province..
        /// </summary>
        public static string PlaceMsg_8_7 {
            get {
                return ResourceManager.GetString("PlaceMsg_8_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is a mountain station at 1,868 m (6,128 ft) of altitude, in a splendid landscape..
        /// </summary>
        public static string PlaceMsg_8_8 {
            get {
                return ResourceManager.GetString("PlaceMsg_8_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is most popular for its golden beach that stretches a mile and some world-class hotels..
        /// </summary>
        public static string PlaceMsg_8_9 {
            get {
                return ResourceManager.GetString("PlaceMsg_8_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A  surfer town with its sandy beaches, sea-side resorts and discos..
        /// </summary>
        public static string PlaceMsg_9_1 {
            get {
                return ResourceManager.GetString("PlaceMsg_9_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bentota is a coastal city located in the Southern Province..
        /// </summary>
        public static string PlaceMsg_9_2 {
            get {
                return ResourceManager.GetString("PlaceMsg_9_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is a mountain station at 1,868 m (6,128 ft) of altitude, in a splendid landscape..
        /// </summary>
        public static string PlaceMsg_9_3 {
            get {
                return ResourceManager.GetString("PlaceMsg_9_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is the commercial capital of the country..
        /// </summary>
        public static string PlaceMsg_9_4 {
            get {
                return ResourceManager.GetString("PlaceMsg_9_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is located in the center of the country amongst the hills of the Kandy Valley..
        /// </summary>
        public static string PlaceMsg_9_5 {
            get {
                return ResourceManager.GetString("PlaceMsg_9_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A  surfer town with its sandy beaches, sea-side resorts and discos..
        /// </summary>
        public static string PlaceMsg_9_6 {
            get {
                return ResourceManager.GetString("PlaceMsg_9_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is the commercial capital of the country..
        /// </summary>
        public static string PlaceMsg_9_7 {
            get {
                return ResourceManager.GetString("PlaceMsg_9_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is most popular for its golden beach that stretches a mile and some world-class hotels..
        /// </summary>
        public static string PlaceMsg_9_8 {
            get {
                return ResourceManager.GetString("PlaceMsg_9_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is most popular for its golden beach that stretches a mile and some world-class hotels..
        /// </summary>
        public static string PlaceMsg_9_9 {
            get {
                return ResourceManager.GetString("PlaceMsg_9_9", resourceCulture);
            }
        }
    }
}
