//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoveCal.Resourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Places {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Places() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoveCal.Resourses.Places", typeof(Places).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batticaloa.
        /// </summary>
        public static string Place_1_1 {
            get {
                return ResourceManager.GetString("Place_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colombo.
        /// </summary>
        public static string Place_1_2 {
            get {
                return ResourceManager.GetString("Place_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adams Peak .
        /// </summary>
        public static string Place_1_3 {
            get {
                return ResourceManager.GetString("Place_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batticaloa.
        /// </summary>
        public static string Place_1_4 {
            get {
                return ResourceManager.GetString("Place_1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dambulla.
        /// </summary>
        public static string Place_1_5 {
            get {
                return ResourceManager.GetString("Place_1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bentota.
        /// </summary>
        public static string Place_1_6 {
            get {
                return ResourceManager.GetString("Place_1_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuwara Eliya.
        /// </summary>
        public static string Place_1_7 {
            get {
                return ResourceManager.GetString("Place_1_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batticaloa.
        /// </summary>
        public static string Place_1_8 {
            get {
                return ResourceManager.GetString("Place_1_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colombo.
        /// </summary>
        public static string Place_1_9 {
            get {
                return ResourceManager.GetString("Place_1_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bentota.
        /// </summary>
        public static string Place_2_1 {
            get {
                return ResourceManager.GetString("Place_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hikkaduwa.
        /// </summary>
        public static string Place_2_2 {
            get {
                return ResourceManager.GetString("Place_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuwara Eliya.
        /// </summary>
        public static string Place_2_3 {
            get {
                return ResourceManager.GetString("Place_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beruwela.
        /// </summary>
        public static string Place_2_4 {
            get {
                return ResourceManager.GetString("Place_2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuwara Eliya.
        /// </summary>
        public static string Place_2_5 {
            get {
                return ResourceManager.GetString("Place_2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bentota.
        /// </summary>
        public static string Place_2_6 {
            get {
                return ResourceManager.GetString("Place_2_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colombo.
        /// </summary>
        public static string Place_2_7 {
            get {
                return ResourceManager.GetString("Place_2_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bentota.
        /// </summary>
        public static string Place_2_8 {
            get {
                return ResourceManager.GetString("Place_2_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuwara Eliya.
        /// </summary>
        public static string Place_2_9 {
            get {
                return ResourceManager.GetString("Place_2_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaffna.
        /// </summary>
        public static string Place_3_1 {
            get {
                return ResourceManager.GetString("Place_3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bentota.
        /// </summary>
        public static string Place_3_2 {
            get {
                return ResourceManager.GetString("Place_3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colombo.
        /// </summary>
        public static string Place_3_3 {
            get {
                return ResourceManager.GetString("Place_3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurunegala.
        /// </summary>
        public static string Place_3_4 {
            get {
                return ResourceManager.GetString("Place_3_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kandy.
        /// </summary>
        public static string Place_3_5 {
            get {
                return ResourceManager.GetString("Place_3_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bentota.
        /// </summary>
        public static string Place_3_6 {
            get {
                return ResourceManager.GetString("Place_3_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurunegala.
        /// </summary>
        public static string Place_3_7 {
            get {
                return ResourceManager.GetString("Place_3_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batticaloa.
        /// </summary>
        public static string Place_3_8 {
            get {
                return ResourceManager.GetString("Place_3_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bentota.
        /// </summary>
        public static string Place_3_9 {
            get {
                return ResourceManager.GetString("Place_3_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batticaloa.
        /// </summary>
        public static string Place_4_1 {
            get {
                return ResourceManager.GetString("Place_4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bentota.
        /// </summary>
        public static string Place_4_2 {
            get {
                return ResourceManager.GetString("Place_4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaffna.
        /// </summary>
        public static string Place_4_3 {
            get {
                return ResourceManager.GetString("Place_4_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colombo.
        /// </summary>
        public static string Place_4_4 {
            get {
                return ResourceManager.GetString("Place_4_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batticaloa.
        /// </summary>
        public static string Place_4_5 {
            get {
                return ResourceManager.GetString("Place_4_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hikkaduwa.
        /// </summary>
        public static string Place_4_6 {
            get {
                return ResourceManager.GetString("Place_4_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kandy.
        /// </summary>
        public static string Place_4_7 {
            get {
                return ResourceManager.GetString("Place_4_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kandy.
        /// </summary>
        public static string Place_4_8 {
            get {
                return ResourceManager.GetString("Place_4_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batticaloa.
        /// </summary>
        public static string Place_4_9 {
            get {
                return ResourceManager.GetString("Place_4_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hikkaduwa.
        /// </summary>
        public static string Place_5_1 {
            get {
                return ResourceManager.GetString("Place_5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hikkaduwa.
        /// </summary>
        public static string Place_5_2 {
            get {
                return ResourceManager.GetString("Place_5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bentota.
        /// </summary>
        public static string Place_5_3 {
            get {
                return ResourceManager.GetString("Place_5_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batticaloa.
        /// </summary>
        public static string Place_5_4 {
            get {
                return ResourceManager.GetString("Place_5_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batticola.
        /// </summary>
        public static string Place_5_5 {
            get {
                return ResourceManager.GetString("Place_5_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kandy.
        /// </summary>
        public static string Place_5_6 {
            get {
                return ResourceManager.GetString("Place_5_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kandy.
        /// </summary>
        public static string Place_5_7 {
            get {
                return ResourceManager.GetString("Place_5_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bentota.
        /// </summary>
        public static string Place_5_8 {
            get {
                return ResourceManager.GetString("Place_5_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galle.
        /// </summary>
        public static string Place_5_9 {
            get {
                return ResourceManager.GetString("Place_5_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colombo.
        /// </summary>
        public static string Place_6_1 {
            get {
                return ResourceManager.GetString("Place_6_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kandy.
        /// </summary>
        public static string Place_6_2 {
            get {
                return ResourceManager.GetString("Place_6_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colombo.
        /// </summary>
        public static string Place_6_3 {
            get {
                return ResourceManager.GetString("Place_6_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuwara Eliya.
        /// </summary>
        public static string Place_6_4 {
            get {
                return ResourceManager.GetString("Place_6_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galle.
        /// </summary>
        public static string Place_6_5 {
            get {
                return ResourceManager.GetString("Place_6_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hikkaduwa.
        /// </summary>
        public static string Place_6_6 {
            get {
                return ResourceManager.GetString("Place_6_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dambulla.
        /// </summary>
        public static string Place_6_7 {
            get {
                return ResourceManager.GetString("Place_6_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuwara Eliya.
        /// </summary>
        public static string Place_6_8 {
            get {
                return ResourceManager.GetString("Place_6_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hikkaduwa.
        /// </summary>
        public static string Place_6_9 {
            get {
                return ResourceManager.GetString("Place_6_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kandy.
        /// </summary>
        public static string Place_7_1 {
            get {
                return ResourceManager.GetString("Place_7_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dambulla.
        /// </summary>
        public static string Place_7_2 {
            get {
                return ResourceManager.GetString("Place_7_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batticola.
        /// </summary>
        public static string Place_7_3 {
            get {
                return ResourceManager.GetString("Place_7_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dambulla.
        /// </summary>
        public static string Place_7_4 {
            get {
                return ResourceManager.GetString("Place_7_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kandy.
        /// </summary>
        public static string Place_7_5 {
            get {
                return ResourceManager.GetString("Place_7_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dambulla.
        /// </summary>
        public static string Place_7_6 {
            get {
                return ResourceManager.GetString("Place_7_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kandy.
        /// </summary>
        public static string Place_7_7 {
            get {
                return ResourceManager.GetString("Place_7_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colombo.
        /// </summary>
        public static string Place_7_8 {
            get {
                return ResourceManager.GetString("Place_7_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuwara Eliya.
        /// </summary>
        public static string Place_7_9 {
            get {
                return ResourceManager.GetString("Place_7_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colombo.
        /// </summary>
        public static string Place_8_1 {
            get {
                return ResourceManager.GetString("Place_8_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuwara Eliya.
        /// </summary>
        public static string Place_8_2 {
            get {
                return ResourceManager.GetString("Place_8_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batticaloa.
        /// </summary>
        public static string Place_8_3 {
            get {
                return ResourceManager.GetString("Place_8_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hikkaduwa.
        /// </summary>
        public static string Place_8_4 {
            get {
                return ResourceManager.GetString("Place_8_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuwara Eliya.
        /// </summary>
        public static string Place_8_5 {
            get {
                return ResourceManager.GetString("Place_8_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beruwela.
        /// </summary>
        public static string Place_8_6 {
            get {
                return ResourceManager.GetString("Place_8_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bentota.
        /// </summary>
        public static string Place_8_7 {
            get {
                return ResourceManager.GetString("Place_8_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuwara Eliya.
        /// </summary>
        public static string Place_8_8 {
            get {
                return ResourceManager.GetString("Place_8_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beruwala.
        /// </summary>
        public static string Place_8_9 {
            get {
                return ResourceManager.GetString("Place_8_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hikkaduwa.
        /// </summary>
        public static string Place_9_1 {
            get {
                return ResourceManager.GetString("Place_9_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bentota.
        /// </summary>
        public static string Place_9_2 {
            get {
                return ResourceManager.GetString("Place_9_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuwara Eliya.
        /// </summary>
        public static string Place_9_3 {
            get {
                return ResourceManager.GetString("Place_9_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colombo.
        /// </summary>
        public static string Place_9_4 {
            get {
                return ResourceManager.GetString("Place_9_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kandy.
        /// </summary>
        public static string Place_9_5 {
            get {
                return ResourceManager.GetString("Place_9_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hikkaduwa.
        /// </summary>
        public static string Place_9_6 {
            get {
                return ResourceManager.GetString("Place_9_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colombo.
        /// </summary>
        public static string Place_9_7 {
            get {
                return ResourceManager.GetString("Place_9_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beruwela.
        /// </summary>
        public static string Place_9_8 {
            get {
                return ResourceManager.GetString("Place_9_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beruwela.
        /// </summary>
        public static string Place_9_9 {
            get {
                return ResourceManager.GetString("Place_9_9", resourceCulture);
            }
        }
    }
}
